config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :users
  root to: "home#show"

  

  mount Thredded::Engine => '/forum'
  
  
  

end

app/models/thredded/user_permissions/write/all.rb
# frozen_string_literal: true
module Thredded
  module UserPermissions
    module Write
      module All
        extend ActiveSupport::Concern
        included { extend ClassMethods }

        # @return [ActiveRecord::Relation<Thredded::Messageboard>] messageboards that the user can post in
        def thredded_can_write_messageboards
          Thredded::Messageboard.all
        end

        module ClassMethods
          # Users that can post to the given messageboards.
          #
          # @param _messageboards [Array<Thredded::Messageboard>]
          # @return [ActiveRecord::Relation<Thredded.user_class>] users that can post to the given messageboards
          def thredded_messageboards_writers(_messageboards)
            all
          end
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  #validates :name, :uniqueness => true, :case_sensitive => false
  validates_uniqueness_of :name, :case_sensitive => false
  
  require 'securerandom'
  
  
  def produce_token(length=32)
    token = SecureRandom.urlsafe_base64(length)
  end
  
  
  def self.search(query)
    where("name like ?", "%#{query}%") 
  end
  
  def to_s
    name
  end

  def self.from_omniauth(auth) 
    
      where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        # maybe make a field called realname and map it to auth.info.name
        user.name = SecureRandom.uuid
        user.realname = auth.info.name
        # then I can map the 'handle' to user.name and have a clean integration with thredded
        user.email = auth.info.email
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        
        if (auth.info.image).to_s == "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
          user.image_url = "http://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=87682042"
        else
          user.image_url = auth.info.image
        end
        
        user.save!
      end

  end


  def admin
  	# This needs to be changed to actually determine
  	# if a user is an admin, this is just a dummy
  	# function.
    self.name != '@DmIn¦Tù€r¦L£~Fèù;'
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
  protect_from_forgery

  protected

  def current_user
     @current_user ||= User.find_by(id: session[:user_id])
  end
  

  def signed_in?
    !!current_user
  end
  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.nil? ? nil : user.id
  end
  
  def confirm_logged_in
    unless session[:user_id]
        flash[:notice] = "Please log in"
        redirect_to :root
        return false
    else
        return true
    end
  end 
  
  # Confirms the correct user.
  def correct_user
    if !(current_user.try(:admin?))
        @user = User.find(params[:id])
        redirect_to(root_url) unless @user == current_user
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id

    
    
    if (current_user)
      if ((current_user.name).to_s).length > 20
        redirect_to edit_user_path(current_user)
      else
         redirect_to root_path
      end
    end

    
  end
  
  def destroy
  	session[:user_id] = nil
    redirect_to root_path
  end
  
  
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_filter :confirm_logged_in, :only => [:show, :edit, :update, :destroy]
    

    before_action :correct_user,   only: [:edit, :update, :destroy]
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    
    def index
        
        @users = User.page(params[:page]).per(6)
        if params[:search]
            @users = @users.search(params[:search]).order("created_at DESC")
        else
            @users = @users.all.order('created_at DESC')
        end
        
    end
    
    def show
    end
    
    def edit
    end
    
    def update
       respond_to do |format|
         if @user.update(user_params)
           format.html { redirect_to @user, notice: 'User was successfully updated.' }
           format.json { render :show, status: :ok, location: @user }
         else
           format.html { render :edit }
           format.json { render json: @user.errors, status: :unprocessable_entity }
         end
        end
    end
    
    def destroy
       @user.destroy
       respond_to do |format|
         format.html { redirect_to signout_path, notice: 'User was successfully destroyed.' }
         format.json { head :no_content }
       end
    end
    
    private
       # Use callbacks to share common setup or constraints between actions.
       def set_user
         @user = User.find(params[:id])
       end
    
       # Never trust parameters from the scary internet, only allow the white list through.
       def user_params
         params.require(:user).permit(:name, :bio, :dob, :phone, :state, :city, :zip, :admin, :image_url, :ban)
       end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def us_states
        [
          ['N/A', 'NA'],
          ['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['District of Columbia', 'DC'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Puerto Rico', 'PR'],
          ['Rhode Island', 'RI'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY']
        ]
    end

    def supper_admin
        @supper_admin = "@Young_Hacks_Academy"
    end
    
    def max_nickname_length
        @max_nickname_length = 20
    end
        
end

app/views/home/show.html.erb
    <% provide(:title, "Home Page") %>
    <% provide(:home, "active") %>

<script type="text/javascript">
  $(document).ready(function(){    
      //Check if the current URL contains '#'
      if(document.URL.indexOf("#")==-1)
      {
          // Set the URL to whatever it was plus "#".
          url = document.URL+"#";
          location = "#";
  
          //Reload the page
          location.reload(true);
      }
  });
</script>

<div class="container">    
    <div class="cover">
      <div class="hi">
          <div class="hovereffect">
              <img class="img-responsive" src="http://i.nextmedia.com.au/Features/eagle_circle_big.png" alt="YHA_logo">
              <div class="overlay">
                 <h2>
                   <div>
                      Young Hacks Academy
                   </div>
                   <hr width="50%">
                   <i class="fa fa-user-secret fa-lg"></i>The Agency
                 </h2>
                 <% if current_user %>
                   <%= link_to raw("<i class='fa fa-newspaper-o fa-lg'></i> Profile"), current_user, :class => "info" %>
                   <%= link_to raw("<i class='fa fa-users fa-lg'></i> Agents"), users_path, :class => "info" %>
                   <%= link_to raw("<i class='fa fa-list-ul fa-lg'></i> DashBoard"), thredded_url, :class => "info"  %>
                 <% else %>
                     <%= link_to raw("<i class='fa fa-google-plus-square fa-lg'></i> Sign In With Google"), "/auth/google_oauth2", class: "info"  %>
                 <% end %>
              </div>
          </div>
      </div>
          <!-- <%#= render "shared/footer" %> -->
    </div>
    
    <div class="tv">
    	  <div class="screen mute" id="tv"></div>
    </div>
    
</div>   


    <!-- About us & Slide Show Grid Section
    <section id="Slide Show">
        <div class="container">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">

              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
              </ol>
          

              <div class="carousel-inner" role="listbox">
          
                <div class="item active">
                  <img src="http://learn2teach.pbworks.com/f/scratchsheet2.jpg">
                  <div class="carousel-caption">
                    <h3></h3>
                    <p></p>
                  </div>
                </div>
                
                <div class="item">
                  <img src="https://udemy-images.udemy.com/course/750x422/60344_92fc_3.jpg">
                  <div class="carousel-caption">
                    <h3></h3>
                    <p></p>
                  </div>
                </div>
                
                <div class="item">
                  <img src="http://4.bp.blogspot.com/-KfMLs-e3rxY/VUXe4VpqZyI/AAAAAAAAAGw/ZhbBLZ3j9hk/s1600/5-reasons-to-code.png">
                  <div class="carousel-caption">
                    <h3></h3>
                    <p></p>
                  </div>
                </div>
                
                <div class="item">
                  <img src="http://www1.pcmag.com/media/images/485120-learn-to-code.jpg?thumb=y&width=740&height=426">
                  <div class="carousel-caption">
                    <h3></h3>
                    <p></p>
                  </div>
                </div>
          
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
    </section>

    //About Section
    <section class="success" id="about">
        <div class="container" id="text">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light" width="75%">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>
                        Young Hacks Academy is a summer camp for ages 6-14 that uses technology to develop real-world leadership skills.
                        A blend of computer programming, problem-solving, and teamwork, YHA teaches kids to build cool video games about big challenges facing us on the local and global level.
                    </p>
                </div>
                <div class="col-lg-4">
                    <p>
                        Encouraging young minds to “turn on” and see how they can become agents of change — future leaders and problem-solvers — through the creative use of technology.   
                    </p>
                </div>
            </div>
        </div>
        <br>
    </section>
-->

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <!--
    <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
    -->
    
    <!-- FOOTER -->
    
    
    

app/views/layouts/thredded/application.html.erb
<% if current_user %>
  <% if current_user.ban == false %>
    <!DOCTYPE html>
    <html>
      <head>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
        
        <title>Thredded | <%= yield :thredded_page_title %></title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <%= stylesheet_link_tag 'thredded' %>
        <%= stylesheet_link_tag 'thredded_app' %>
        <%= csrf_meta_tag %>
        <%= javascript_include_tag 'thredded' %>
        <%= javascript_include_tag 'thredded_app' %>
        <%== Gravatar.prefetch_dns %>
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        
      </head>
      <body>
        <!-- MAIN -->
        <div class="main_content_thredded <%= controller.controller_name %>">
          <%= yield %>
        </div>
      </body>
    </html>
  <% else %>
    <script>
        alert("You have been banned from the system please contact Geoff Abbott.");
        window.location.href = '/signout';
    </script>
  <% end %>
<% else %>
  <script> history.back(); </script>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer navbar-fixed-bottom -->
    <footer class="footer navbar-fixed-bottom text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3><i class="fa fa-map-marker fa-lg"></i> Location </h3>
                        <p>Current <a href="http://younghacks.com/2016-locations/"> Camps</a></p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3><i class="fa fa-eye fa-lg"></i> Afterschool Program</h3>
                        <p>REGISTER <a href="http://younghacks.com/after-school-program/"> NOW</a></p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3><i class="fa fa-university fa-lg"></i> About YHA</h3>
                        <p>Created by <a href="http://younghacks.com/"> Younghacks</a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright <i class="fa fa-copyright fa-lg"></i> Young Hacks Academy
                    </div>
                </div>
            </div>
        </div>
        <br>
    </footer>
    

app/views/shared/_homeNavbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigationbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>

          </button>
      <%= link_to raw("<i class='fa fa-user-secret fa-lg'></i> &nbsp; Young Hacks Academy"), root_path, class: "navbar-brand" %>
      
    </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigationbar">
            <ul class="nav navbar-nav navbar-right">
                
                <% if current_user %>
                  <li class="<%= yield(:agents) %>"> <%= link_to raw("<i class='fa fa-users fa-lg'></i> Agents"), users_path %></li>
                  <li class="<%= yield(:dashboard) %>"> <%= link_to raw("<i class='fa fa-list-ul fa-lg'></i> DashBoard"), thredded_url %> </li>
                <% end %>
                
                <li>
                  <span>
                    <% if current_user %>
                      <li>
                        <div class="dropdown">
                          <button class="btn btn-defualt dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-user-secret fa-lg">&nbsp;<%= current_user.name %></i> 
                          <span class="caret"></span></button>
                          <ul class="dropdown-menu">
                            <li><%= link_to raw("<i class='fa fa-newspaper-o fa-lg'></i> Show Profile"), current_user %></li>
                            <li><%= link_to raw("<i class='fa fa-pencil-square-o fa-lg'></i> Edit Profile"), edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li><%= link_to raw("</span><i class='fa fa-power-off fa-lg'></i> Sign Out"), signout_path %> </li>
                          </ul>
                        </div>
                      </li>
                    <% else %>
                      <%= link_to raw("<i class='fa fa-google-plus-square fa-lg'></i> Sign In With Google"), "/auth/google_oauth2", id: "sign_in", class: "btn btn-danger"  %>
                    <% end %>
                  </span>
                </li>
                <li><span>&nbsp;</span></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/shared/_newUserNavbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigationbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand"> <i class='fa fa-user-secret fa-lg'></i> &nbsp; Young Hacks Academy  </a>
      </div>

    </div>
    <!-- /.container-fluid -->
</nav>

app/views/shared/_userNavbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigationbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to raw("<i class='fa fa-user-secret fa-lg'> </i> &nbsp; Young Hacks Academy"), root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigationbar">
          
          <ul class="nav navbar-nav navbar-right">
            
            <li class="<%= yield(:home) %>"><%= link_to raw("<i class='fa fa-home fa-lg'></i> Home"), root_path %></li>
            <li class="<%= yield(:agents) %>"> <%= link_to raw("<i class='fa fa-users fa-lg'></i> Agents"), users_path %></li>
            <li class="<%= yield(:dashboard) %>"> <%= link_to raw("<i class='fa fa-list-ul fa-lg'></i> DashBoard"), thredded_url %> </li>
   
            <li>
              <span>
                <% if current_user %>
                  <li>
                    <div class="dropdown">
                      <button class="btn btn-defualt dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-user-secret fa-lg"> &nbsp;<%= current_user.name %></i> 
                      <span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li><%= link_to raw("<i class='fa fa-newspaper-o fa-lg'></i> Show Profile"), current_user %></li>
                        <li><%= link_to raw("<i class='fa fa-pencil-square-o fa-lg'></i> Edit Profile"), edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li><%= link_to raw("</span><i class='fa fa-power-off fa-lg'></i> Sign Out"), signout_path %> </li>
                      </ul>
                    </div>
                  </li>
                <% else %>
                  <%= link_to raw("<i class='fa fa-google-plus-square fa-lg'></i> Sign In With Google"), "/auth/google_oauth2", id: "sign_in", class: "btn btn-danger"  %>
                <% end %>
              </span>
            </li>
            <li><span>&nbsp;</span></li>
          </ul>
        </div>
        
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/thredded/messageboards/index.html.erb
<% content_for :thredded_page_title, 'Messageboards' %>
<% content_for :thredded_page_id, 'thredded--messageboards-index' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>

<%= thredded_page do %>
  
  
  <section class="thredded--main-section thredded--messageboards">
    <% if policy(Thredded::Messageboard.new).create? && current_user.admin? %>
      <div class="thredded--messageboard--create">
        <a class="thredded--button" href="<%= new_messageboard_path %>">Create a New Messageboard</a>
      </div>
      <br>
    <% end %>
  
    <%= render @messageboards %>
    
    
  </section>
  
<% end %>

app/views/thredded/messageboards/new.html.erb
<% if current_user.admin? %>
  <% content_for :thredded_page_title, 'Create a New Messageboard' %>
  <% content_for :thredded_page_id, 'thredded--messageboards-new' %>
  <% content_for :thredded_breadcrumbs do %>
    <ul class="thredded--navigation-breadcrumbs">
      <li>Create a New Messageboard</li>
    </ul>
  <% end %>
  
  <%= thredded_page do %>
  <br><br>
    <%= form_for @messageboard, html: { class: 'thredded--form' } do |f| %>
      <ul class="thredded--form-list">
        <li>
          <%= f.label :name %>
          <%= f.text_field :name, required: true, :maxlength => "30" %>
        </li>
        <li>
          <%= f.label :description %>
          <%= f.text_field :description %>
        </li>
  
        <li><%= f.submit 'Create New Messageboard', class: 'thredded--form--submit' %></li>
      </ul>
    <% end %>
  <% end %>
  
<% else %>
  <script> history.back();  </script>
<% end %>  

app/views/thredded/search/_form.html.erb
<%= form_tag search_path(messageboard), :class => 'thredded--form search_bar' , method: 'get' do %> <!-- thredded--form thredded--navigation--search-->
    <%= text_field_tag :q, @query,
                     type:        'search',
                     required:    true,
                     # If there are no results the user will likely want to change the query, so auto-focus.
                     autofocus:   @query.presence && !@topics.presence,
                     placeholder: 'Search . . .' %>
    
<% end %>

app/views/thredded/topics/_header.html.erb
<header class="thredded--topic-header">
  <h1 class="thredded--topic-header--title"><%= topic.title %></h1>
  <cite class="thredded--topic-header--started-by">
    <%= t 'thredded.topics.started_by_html',
          time_ago: time_ago(topic.created_at),
          user:     user_link(topic.user) %>
  </cite>
  
  
  <div>
    <% if ( (topic.can_update? && (thredded_current_user.name).to_s == (topic.user).to_s) ) || current_user.admin? == true %>
      <%= link_to t('thredded.topics.edit'), topic.edit_path,
                  class: 'thredded--topic-header--edit-topic' %>
    <span> &nbsp; | &nbsp; </span>
    <% end %>
    
    <% if ( topic.can_destroy? && (thredded_current_user.name).to_s == (@topic.user).to_s )|| current_user.admin? == true %>  
        <%= form_tag topic.destroy_path, method: :delete, :style => "display:inline;" do %>
          <%= submit_tag 'Delete Topic', class: 'thredded--form--delete', :style => "display:inline;" %>
        <% end %>
    <% end %>
  </div>
<hr>    
</header>

app/views/thredded/topics/_topic.html.erb
<%= content_tag :article,
                id:    dom_id(topic),
                class: ['thredded--topics--topic', topic_css_classes(topic)] do %>
                
    <div class="thredded--topics--posts-count"><%= topic.posts_count %></div>

    <h1 class="thredded--topics--title">
      <%= link_to topic.title, topic.path %>
    </h1>
  
    <span>&nbsp;</span>
    
    <% if topic.categories.any? %>
      <ul class="thredded--topics--categories">
        <%= render topic.categories %>
      </ul>
    <% end %>
  
    <cite class="thredded--topics--updated-by">
      <%= time_ago topic.updated_at %>
      <%= user_link topic.last_user %>
    </cite>
  
    <cite class="thredded--topics--started-by">
      <%= time_ago topic.created_at %>
      <%= user_link topic.user %>
    </cite>
    
<% end %>

app/views/thredded/topics/edit.html.erb
<% if  (thredded_current_user.name).to_s == (@topic.user).to_s || current_user.admin? == true %>
<% content_for :thredded_page_title, t('thredded.nav.edit_private_topic') %>
<% content_for :thredded_page_id, 'thredded--edit-topic' %>
<% content_for :thredded_breadcrumbs do %>
  <ul class="thredded--navigation-breadcrumbs">
    <li><%= link_to t('thredded.nav.all_messageboards'), messageboards_path %></li>
    <li><%= link_to messageboard.name, messageboard_topics_path(@topic.messageboard, @topic) %></li>
    <li><%= link_to @topic.title, topic_path(@topic) %></li>
    <li><%= link_to t('thredded.nav.edit_topic'), edit_messageboard_topic_path(@topic.messageboard, @topic) %></li>
  </ul>
<% end %>

<%= thredded_page do %>
  <%= form_for [@topic.messageboard, @topic],
               html: { class: 'thredded--form thredded--is-expanded', 'data-thredded-topic-form' => true } do |form| %>
    <ul class="thredded--form-list on-top edit_bar">

      <li class="title">
        <%= form.label :title, t('thredded.topics.form.title_label') %>
        <%= form.text_field :title,
                            placeholder: t('thredded.topics.form.title_placeholder'),
                            autofocus:   true,
                            required:    true %>
      </li>

      <% if form.object.categories.any? %>
        <li class="category">
          <%= form.select :category_ids, form.object.category_options, {},
                          multiple:          true,
                          'data-placeholder' => t('thredded.topics.form.categories_placeholder') %>
        </li>
      <% end %>

      <%= render 'thredded/topics/topic_form_admin_options', form: form %>

      <li>
        <button type="submit" class="thredded--form--submit">
          <%= t('thredded.topics.form.update_btn') %>
        </button>
      </li>
  <% end %>
  </ul>
<% end %>

<% else %>

  <script>history.back();</script>
  
<% end %>

app/views/thredded/topics/show.html.erb
<% topic = @posts.topic %>
<% content_for :thredded_page_title, topic.title %>
<% content_for :thredded_page_id, 'thredded--topic-show' %>
<% content_for :thredded_breadcrumbs, render('thredded/shared/breadcrumbs') %>

<%= thredded_page do %>
  
    <%= content_tag :section,
                    id: dom_id(topic),
                    class: ['thredded--main-section', 'thredded--topic', *topic_css_classes(topic)] do %>
                    
      <%= render 'thredded/topics/header', topic: topic %>

      <%= render partial: 'thredded/posts/post', collection: @posts, cached: true, object: @switch %>


      <% if policy(@new_post).create? %>
        <div class="thredded--post-form--wrapper">
          <h3 class="thredded--post-form--title">Add a post</h3>
          <%= render 'thredded/posts/form',
                     topic:       topic,
                     post:        @new_post,
                     button_text: t('thredded.posts.form.create_btn') %>
        </div>
      <% end %>
    <% end %>
    

  <footer>
    <%= paginate @posts %>
  </footer>
<% end %>